version: "3.4"
services:
  web:
    build:
      context: ./
      dockerfile: Travsystem.Web/Dockerfile
    image: jockesv/travsystem-web
    networks: 
      - webnet
    ports:
      - 80:5000

networks:
  webnet:
    driver: overlay
    attachable: true    