//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.239
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=4.0.30319.1.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
[System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
public partial class issuer {
    
    private betcouponsType betcouponsField;
    
    private string companyField;
    
    private string productField;
    
    private string versionField;
    
    private System.DateTime createddateField;
    
    private bool createddateFieldSpecified;
    
    private System.DateTime createdtimeField;
    
    private bool createdtimeFieldSpecified;
    
    private string schemaversionField;
    
    public issuer() {
        this.schemaversionField = "ATG File Betting XSD ver 1.6";
    }
    
    /// <remarks/>
    public betcouponsType betcoupons {
        get {
            return this.betcouponsField;
        }
        set {
            this.betcouponsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string company {
        get {
            return this.companyField;
        }
        set {
            this.companyField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string product {
        get {
            return this.productField;
        }
        set {
            this.productField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string version {
        get {
            return this.versionField;
        }
        set {
            this.versionField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="date")]
    public System.DateTime createddate {
        get {
            return this.createddateField;
        }
        set {
            this.createddateField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool createddateSpecified {
        get {
            return this.createddateFieldSpecified;
        }
        set {
            this.createddateFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="time")]
    public System.DateTime createdtime {
        get {
            return this.createdtimeField;
        }
        set {
            this.createdtimeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool createdtimeSpecified {
        get {
            return this.createdtimeFieldSpecified;
        }
        set {
            this.createdtimeFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string schemaversion {
        get {
            return this.schemaversionField;
        }
        set {
            this.schemaversionField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class betcouponsType {
    
    private v86CouponType[] v86CouponField;
    
    private v75CouponType[] v75CouponField;
    
    private v65CouponType[] v65CouponField;
    
    private v64CouponType[] v64CouponField;
    
    private v5CouponType[] v5CouponField;
    
    private v4CouponType[] v4CouponField;
    
    private v3CouponType[] v3CouponField;
    
    private DDCouponType[] dDCouponField;
    
    private LDCouponType[] lDCouponField;
    
    private VPCouponType[] vPCouponField;
    
    private kombCouponType[] kombCouponField;
    
    private tvillingCouponType[] tvillingCouponField;
    
    private trioCouponType[] trioCouponField;
    
    private raketCouponType[] raketCouponField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("v86Coupon")]
    public v86CouponType[] v86Coupon {
        get {
            return this.v86CouponField;
        }
        set {
            this.v86CouponField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("v75Coupon")]
    public v75CouponType[] v75Coupon {
        get {
            return this.v75CouponField;
        }
        set {
            this.v75CouponField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("v65Coupon")]
    public v65CouponType[] v65Coupon {
        get {
            return this.v65CouponField;
        }
        set {
            this.v65CouponField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("v64Coupon")]
    public v64CouponType[] v64Coupon {
        get {
            return this.v64CouponField;
        }
        set {
            this.v64CouponField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("v5Coupon")]
    public v5CouponType[] v5Coupon {
        get {
            return this.v5CouponField;
        }
        set {
            this.v5CouponField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("v4Coupon")]
    public v4CouponType[] v4Coupon {
        get {
            return this.v4CouponField;
        }
        set {
            this.v4CouponField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("v3Coupon")]
    public v3CouponType[] v3Coupon {
        get {
            return this.v3CouponField;
        }
        set {
            this.v3CouponField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("DDCoupon")]
    public DDCouponType[] DDCoupon {
        get {
            return this.dDCouponField;
        }
        set {
            this.dDCouponField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("LDCoupon")]
    public LDCouponType[] LDCoupon {
        get {
            return this.lDCouponField;
        }
        set {
            this.lDCouponField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("VPCoupon")]
    public VPCouponType[] VPCoupon {
        get {
            return this.vPCouponField;
        }
        set {
            this.vPCouponField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("kombCoupon")]
    public kombCouponType[] kombCoupon {
        get {
            return this.kombCouponField;
        }
        set {
            this.kombCouponField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("tvillingCoupon")]
    public tvillingCouponType[] tvillingCoupon {
        get {
            return this.tvillingCouponField;
        }
        set {
            this.tvillingCouponField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("trioCoupon")]
    public trioCouponType[] trioCoupon {
        get {
            return this.trioCouponField;
        }
        set {
            this.trioCouponField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("raketCoupon")]
    public raketCouponType[] raketCoupon {
        get {
            return this.raketCouponField;
        }
        set {
            this.raketCouponField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class v86CouponType {
    
    private legType[] legField;
    
    private string couponidField;
    
    private string trackcodeField;
    
    private System.DateTime dateField;
    
    private string betmultiplierField;
    
    public v86CouponType() {
        this.betmultiplierField = "1";
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("leg")]
    public legType[] leg {
        get {
            return this.legField;
        }
        set {
            this.legField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
    public string couponid {
        get {
            return this.couponidField;
        }
        set {
            this.couponidField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
    public string trackcode {
        get {
            return this.trackcodeField;
        }
        set {
            this.trackcodeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="date")]
    public System.DateTime date {
        get {
            return this.dateField;
        }
        set {
            this.dateField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
    [System.ComponentModel.DefaultValueAttribute("1")]
    public string betmultiplier {
        get {
            return this.betmultiplierField;
        }
        set {
            this.betmultiplierField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class legType {
    
    private string legnoField;
    
    private string marksField;
    
    private string r1Field;
    
    private string r2Field;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
    public string legno {
        get {
            return this.legnoField;
        }
        set {
            this.legnoField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string marks {
        get {
            return this.marksField;
        }
        set {
            this.marksField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
    public string r1 {
        get {
            return this.r1Field;
        }
        set {
            this.r1Field = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
    public string r2 {
        get {
            return this.r2Field;
        }
        set {
            this.r2Field = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class raketStageType {
    
    private string racenoField;
    
    private string selectionField;
    
    private bool winField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
    public string raceno {
        get {
            return this.racenoField;
        }
        set {
            this.racenoField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
    public string selection {
        get {
            return this.selectionField;
        }
        set {
            this.selectionField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public bool win {
        get {
            return this.winField;
        }
        set {
            this.winField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class raketCouponType {
    
    private raketStageType[] raketStageField;
    
    private string couponidField;
    
    private System.DateTime dateField;
    
    private string trackcodeField;
    
    private string systemtypeField;
    
    private string stagesField;
    
    private string stakeField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("raketStage")]
    public raketStageType[] raketStage {
        get {
            return this.raketStageField;
        }
        set {
            this.raketStageField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
    public string couponid {
        get {
            return this.couponidField;
        }
        set {
            this.couponidField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="date")]
    public System.DateTime date {
        get {
            return this.dateField;
        }
        set {
            this.dateField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
    public string trackcode {
        get {
            return this.trackcodeField;
        }
        set {
            this.trackcodeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string systemtype {
        get {
            return this.systemtypeField;
        }
        set {
            this.systemtypeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
    public string stages {
        get {
            return this.stagesField;
        }
        set {
            this.stagesField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
    public string stake {
        get {
            return this.stakeField;
        }
        set {
            this.stakeField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class trioCouponType {
    
    private string couponidField;
    
    private System.DateTime dateField;
    
    private string trackcodeField;
    
    private string racenoField;
    
    private string marks1stField;
    
    private string marks2ndField;
    
    private string marks3rdField;
    
    private string stakeField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
    public string couponid {
        get {
            return this.couponidField;
        }
        set {
            this.couponidField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="date")]
    public System.DateTime date {
        get {
            return this.dateField;
        }
        set {
            this.dateField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
    public string trackcode {
        get {
            return this.trackcodeField;
        }
        set {
            this.trackcodeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
    public string raceno {
        get {
            return this.racenoField;
        }
        set {
            this.racenoField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string marks1st {
        get {
            return this.marks1stField;
        }
        set {
            this.marks1stField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string marks2nd {
        get {
            return this.marks2ndField;
        }
        set {
            this.marks2ndField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string marks3rd {
        get {
            return this.marks3rdField;
        }
        set {
            this.marks3rdField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
    public string stake {
        get {
            return this.stakeField;
        }
        set {
            this.stakeField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class tvillingCouponType {
    
    private string couponidField;
    
    private System.DateTime dateField;
    
    private string trackcodeField;
    
    private string racenoField;
    
    private string marksField;
    
    private string umarksField;
    
    private string stakeField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
    public string couponid {
        get {
            return this.couponidField;
        }
        set {
            this.couponidField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="date")]
    public System.DateTime date {
        get {
            return this.dateField;
        }
        set {
            this.dateField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
    public string trackcode {
        get {
            return this.trackcodeField;
        }
        set {
            this.trackcodeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
    public string raceno {
        get {
            return this.racenoField;
        }
        set {
            this.racenoField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string marks {
        get {
            return this.marksField;
        }
        set {
            this.marksField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string umarks {
        get {
            return this.umarksField;
        }
        set {
            this.umarksField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
    public string stake {
        get {
            return this.stakeField;
        }
        set {
            this.stakeField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class kombCouponType {
    
    private string couponidField;
    
    private System.DateTime dateField;
    
    private string trackcodeField;
    
    private string racenoField;
    
    private string marks1stField;
    
    private string marks2ndField;
    
    private string stakeField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
    public string couponid {
        get {
            return this.couponidField;
        }
        set {
            this.couponidField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="date")]
    public System.DateTime date {
        get {
            return this.dateField;
        }
        set {
            this.dateField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
    public string trackcode {
        get {
            return this.trackcodeField;
        }
        set {
            this.trackcodeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
    public string raceno {
        get {
            return this.racenoField;
        }
        set {
            this.racenoField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string marks1st {
        get {
            return this.marks1stField;
        }
        set {
            this.marks1stField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string marks2nd {
        get {
            return this.marks2ndField;
        }
        set {
            this.marks2ndField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
    public string stake {
        get {
            return this.stakeField;
        }
        set {
            this.stakeField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class VPCouponType {
    
    private string couponidField;
    
    private System.DateTime dateField;
    
    private string trackcodeField;
    
    private string racenoField;
    
    private string marksField;
    
    private bool winbetField;
    
    private bool showbetField;
    
    private string stakeField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
    public string couponid {
        get {
            return this.couponidField;
        }
        set {
            this.couponidField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="date")]
    public System.DateTime date {
        get {
            return this.dateField;
        }
        set {
            this.dateField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
    public string trackcode {
        get {
            return this.trackcodeField;
        }
        set {
            this.trackcodeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
    public string raceno {
        get {
            return this.racenoField;
        }
        set {
            this.racenoField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string marks {
        get {
            return this.marksField;
        }
        set {
            this.marksField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public bool winbet {
        get {
            return this.winbetField;
        }
        set {
            this.winbetField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public bool showbet {
        get {
            return this.showbetField;
        }
        set {
            this.showbetField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
    public string stake {
        get {
            return this.stakeField;
        }
        set {
            this.stakeField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class LDCouponType {
    
    private string couponidField;
    
    private System.DateTime dateField;
    
    private string marks1Field;
    
    private string marks2Field;
    
    private string stakeField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
    public string couponid {
        get {
            return this.couponidField;
        }
        set {
            this.couponidField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="date")]
    public System.DateTime date {
        get {
            return this.dateField;
        }
        set {
            this.dateField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string marks1 {
        get {
            return this.marks1Field;
        }
        set {
            this.marks1Field = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string marks2 {
        get {
            return this.marks2Field;
        }
        set {
            this.marks2Field = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
    public string stake {
        get {
            return this.stakeField;
        }
        set {
            this.stakeField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class DDCouponType {
    
    private string couponidField;
    
    private System.DateTime dateField;
    
    private string marks1Field;
    
    private string marks2Field;
    
    private string stakeField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
    public string couponid {
        get {
            return this.couponidField;
        }
        set {
            this.couponidField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="date")]
    public System.DateTime date {
        get {
            return this.dateField;
        }
        set {
            this.dateField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string marks1 {
        get {
            return this.marks1Field;
        }
        set {
            this.marks1Field = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string marks2 {
        get {
            return this.marks2Field;
        }
        set {
            this.marks2Field = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
    public string stake {
        get {
            return this.stakeField;
        }
        set {
            this.stakeField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class v3CouponType {
    
    private string couponidField;
    
    private System.DateTime dateField;
    
    private string trackcodeField;
    
    private string marks1Field;
    
    private string marks2Field;
    
    private string marks3Field;
    
    private string betmultiplierField;
    
    public v3CouponType() {
        this.betmultiplierField = "1";
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
    public string couponid {
        get {
            return this.couponidField;
        }
        set {
            this.couponidField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="date")]
    public System.DateTime date {
        get {
            return this.dateField;
        }
        set {
            this.dateField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
    public string trackcode {
        get {
            return this.trackcodeField;
        }
        set {
            this.trackcodeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string marks1 {
        get {
            return this.marks1Field;
        }
        set {
            this.marks1Field = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string marks2 {
        get {
            return this.marks2Field;
        }
        set {
            this.marks2Field = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string marks3 {
        get {
            return this.marks3Field;
        }
        set {
            this.marks3Field = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
    [System.ComponentModel.DefaultValueAttribute("1")]
    public string betmultiplier {
        get {
            return this.betmultiplierField;
        }
        set {
            this.betmultiplierField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class v4CouponType {
    
    private legType[] legField;
    
    private string couponidField;
    
    private System.DateTime dateField;
    
    private string trackcodeField;
    
    private string betmultiplierField;
    
    public v4CouponType() {
        this.betmultiplierField = "1";
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("leg")]
    public legType[] leg {
        get {
            return this.legField;
        }
        set {
            this.legField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
    public string couponid {
        get {
            return this.couponidField;
        }
        set {
            this.couponidField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="date")]
    public System.DateTime date {
        get {
            return this.dateField;
        }
        set {
            this.dateField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
    public string trackcode {
        get {
            return this.trackcodeField;
        }
        set {
            this.trackcodeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
    [System.ComponentModel.DefaultValueAttribute("1")]
    public string betmultiplier {
        get {
            return this.betmultiplierField;
        }
        set {
            this.betmultiplierField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class v5CouponType {
    
    private legType[] legField;
    
    private string couponidField;
    
    private System.DateTime dateField;
    
    private string trackcodeField;
    
    private string betmultiplierField;
    
    public v5CouponType() {
        this.betmultiplierField = "1";
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("leg")]
    public legType[] leg {
        get {
            return this.legField;
        }
        set {
            this.legField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
    public string couponid {
        get {
            return this.couponidField;
        }
        set {
            this.couponidField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="date")]
    public System.DateTime date {
        get {
            return this.dateField;
        }
        set {
            this.dateField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
    public string trackcode {
        get {
            return this.trackcodeField;
        }
        set {
            this.trackcodeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
    [System.ComponentModel.DefaultValueAttribute("1")]
    public string betmultiplier {
        get {
            return this.betmultiplierField;
        }
        set {
            this.betmultiplierField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class v64CouponType {
    
    private legType[] legField;
    
    private string couponidField;
    
    private System.DateTime dateField;
    
    private string betmultiplierField;
    
    private bool v6Field;
    
    public v64CouponType() {
        this.betmultiplierField = "1";
        this.v6Field = false;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("leg")]
    public legType[] leg {
        get {
            return this.legField;
        }
        set {
            this.legField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
    public string couponid {
        get {
            return this.couponidField;
        }
        set {
            this.couponidField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="date")]
    public System.DateTime date {
        get {
            return this.dateField;
        }
        set {
            this.dateField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
    [System.ComponentModel.DefaultValueAttribute("1")]
    public string betmultiplier {
        get {
            return this.betmultiplierField;
        }
        set {
            this.betmultiplierField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    [System.ComponentModel.DefaultValueAttribute(false)]
    public bool v6 {
        get {
            return this.v6Field;
        }
        set {
            this.v6Field = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class v65CouponType {
    
    private legType[] legField;
    
    private string couponidField;
    
    private System.DateTime dateField;
    
    private string betmultiplierField;
    
    public v65CouponType() {
        this.betmultiplierField = "1";
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("leg")]
    public legType[] leg {
        get {
            return this.legField;
        }
        set {
            this.legField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
    public string couponid {
        get {
            return this.couponidField;
        }
        set {
            this.couponidField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="date")]
    public System.DateTime date {
        get {
            return this.dateField;
        }
        set {
            this.dateField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
    [System.ComponentModel.DefaultValueAttribute("1")]
    public string betmultiplier {
        get {
            return this.betmultiplierField;
        }
        set {
            this.betmultiplierField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class v75CouponType {
    
    private legType[] legField;
    
    private string couponidField;
    
    private System.DateTime dateField;
    
    private string betmultiplierField;
    
    public v75CouponType() {
        this.betmultiplierField = "1";
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("leg")]
    public legType[] leg {
        get {
            return this.legField;
        }
        set {
            this.legField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
    public string couponid {
        get {
            return this.couponidField;
        }
        set {
            this.couponidField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="date")]
    public System.DateTime date {
        get {
            return this.dateField;
        }
        set {
            this.dateField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
    [System.ComponentModel.DefaultValueAttribute("1")]
    public string betmultiplier {
        get {
            return this.betmultiplierField;
        }
        set {
            this.betmultiplierField = value;
        }
    }
}
